In [1]:
import randomvar
import numpy as np

In [9]:

def multi_apply(Fs, V) :
   return lambda  n : np.array([[function_(value) for function_ in Fs] for value in V(n)])
# V(n) liste des échantillon , value : un échantillon .

In [10]:
U = randomvar.uniform()
V = randomvar.apply_array(lambda x : (10*x).astype(int), U)
K = multi_apply([lambda x : x, lambda x : x**2, lambda x : 2*x+1, lambda x : 7*x], V)

randomvar.display(K, 'K')

K :
   [ 8 64 17 56]
   [ 4 16  9 28]
   [ 6 36 13 42]
   [1 1 3 7]
   [ 8 64 17 56]
   [ 3  9  7 21]
   [ 2  4  5 14]
   [ 2  4  5 14]
   [ 5 25 11 35]
   [0 0 1 0]
